spring:
  datasource:
    url: jdbc:mysql://geekyops-devops.cyv0t6hgb3zg.ap-south-1.rds.amazonaws.com:3306/base?useSSL=false 
    username: geekyops 
    password: Gops0608
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 45000
      keepalive-time: 40000
      idle-timeout: 35000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect